import {writeFileSync} from "fs";
import {join} from "path";

import Ajv from "ajv";
import addFormats from "ajv-formats";
import standaloneCode from "ajv/dist/standalone";

import schema = require("./schema.json");

// Generate a function that validates the Keystore schema.
// Write the function to a file in the source.

const OUTPUT_DIR = join(__dirname, "../src");
const OUTPUT_SOURCE_FILE = join(OUTPUT_DIR, "schema-validation-generated.ts");

// Initialize ajv instance
const ajv = new Ajv({
  schemas: [schema],
  code: {
    source: true,
    esm: true,
  }
});
addFormats(ajv);

// The output code is minified vanilla javascript and uses the cute pattern of attaching errors to the exported function as a property.
// The easiest way to treat this is to just ts-ignore the whole output and wrap the function with a handcrafted type.
const moduleCode = `
// This file was generated by /scripts/schema-validation-codegen.ts
// Do not modify this file by hand.

/* eslint-disable */
// @ts-ignore
` + standaloneCode(ajv, {
  Keystore: "#/definitions/Keystore",
});

writeFileSync(OUTPUT_SOURCE_FILE, moduleCode)
